import { StyleSheet } from "react-native"; 'react-native';


export const styles = StyleSheet.create({
     container:{
          backgroundColor:'#0D0D0D',
          flex:1,
     },
     imageContainer:{
          height:200,
          justifyContent:'center',
          alignItems:'center',
          paddingTop:20
     },
     containerList:{
          flex:1,
          alignItems:'center',
          paddingHorizontal:20,
          backgroundColor:'#262626'
     },
     addContainer:{
          marginTop:-30,
          flexDirection:'row',
          height:54, 
          width:327,
     }, 
     button:{
          alignItems:'center',
          justifyContent:'center',
          fontSize:20,
          width:52,
          height:52,
          backgroundColor:'#1E6F9F',
          color:'white', 
          borderRadius:6
     }, 
     input:{
          flex:1, 
          marginRight:10, 
          backgroundColor:'#333333',
          borderColor:'#0d0d0d',
          borderWidth:1,
          borderRadius:6, 
          alignItems:'center', 
          textAlign:'center', 
          color:'white'
     }, 
     status:{
          width:327, 
          height:54,
          marginTop:38, 
          flexDirection:'row', 
          alignItems:'center',
          justifyContent:'space-between', 
     }, 
     detailsStatus:{
          flexDirection:'row', 
          alignItems:'center', 
          justifyContent:'center',
          gap:6
     }, 
     textOne:{
          color:'#4EA8DE',
          fontSize:16
     }, 
     textTwo:{
          color:'#8284FA',
          fontSize:16
     },
     detail:{
          alignItems:'center',
          justifyContent:'center',
          backgroundColor:'#808080', 
          color:'white',
          width:25,
          height:19,
          borderRadius:1000,
     }, 
     list:{
          marginBottom:180
     }
});
